objectionary/eo-collections

- .rultor.yml
- README.md
> description

- pom.xml
>  fixed fail on Windows

- src/main/eo/org/eolang/collections/bytes-as-array.eo
- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/bytes-as-array-tests.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> to move list from eo-runtime

- pom.xml
- src/main/eo/org/eolang/collections/map.eo
- src/main/eo/org/eolang/collections/multimap.eo
- src/main/java/EOorg/EOeolang/EOcollections/EOmultimap$EOrebuild.java
- src/main/java/EOorg/EOeolang/EOcollections/package-info.java
- src/test/eo/org/eolang/collections/bytes-as-array-tests.eo
- src/test/eo/org/eolang/collections/list-tests.eo
- src/test/eo/org/eolang/collections/map-tests.eo
- src/test/eo/org/eolang/collections/multimap-tests.eo
> to move map from eo-runtime

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
@Graur , please review. 
I implemented list.found.
> List found

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
@Graur , please review.
I rewrited `with` attribute for `list` according to #28
> 28 rewrite

- pom.xml
- src/test/eo/org/eolang/collections/multimap-tests.eo
> EO up to 0.28.2

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
https://github.com/objectionary/eo-collections/issues/14
> list.sorted implemented

- src/main/eo/org/eolang/collections/list.eo
@Graur please take a look
closing: #22 
I removed reducei
> 22 removed reducei

- src/main/eo/org/eolang/collections/list.eo
@Graur please review
I removed deprecated `map`  according to #24
> 24 removed map

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> Added `list.filteredi` to list

- src/test/eo/org/eolang/collections/multimap-tests.eo
> fixed multimap conversion string to hash and removed nop object

- pom.xml
- src/test/eo/org/eolang/collections/list-tests.eo
> Added stack size option

- pom.xml
- src/main/eo/org/eolang/collections/list.eo
- src/main/eo/org/eolang/collections/multimap.eo
- src/test/eo/org/eolang/collections/multimap-tests.eo
Closes: #87 
What's done:
- removed unnecessary parenthesis
- set up failOnWarning flag to true
> removed unnecessary parenthesis

- src/main/eo/org/eolang/collections/list.eo
- src/main/java/EOorg/EOeolang/EOcollections/EOlist$EOinflated.java
- src/test/eo/org/eolang/collections/list-tests.eo
Closes: https://github.com/objectionary/eo-collections/issues/99
> text.inflated implemented

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> list.inflated returns list object

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
- src/test/eo/org/eolang/collections/map-tests.eo
- src/test/eo/org/eolang/collections/multimap-tests.eo
> Redundant parentheses removed

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
Closes: #114
What's done:
- renamed `list.found` object to `list.index-of`
> #114 - list.index-of

- src/main/eo/org/eolang/collections/range.eo
- src/test/eo/org/eolang/collections/range-tests.eo
> Introduced range (#122)

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> Fixed `list.sorted` and unwrap tests (#85)

- src/main/eo/org/eolang/collections/set.eo
- src/test/eo/org/eolang/collections/set-tests.eo
> Intoduced set (#120)

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
Closes: #118
Implemented list.contains
> list.contains object

- src/main/eo/org/eolang/collections/range.eo
- src/test/eo/org/eolang/collections/range-tests.eo
> Range without function

- src/main/eo/org/eolang/collections/list.eo
- src/main/eo/org/eolang/collections/map.eo
- src/main/eo/org/eolang/collections/multimap.eo
> #144 adjust for new grammar

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> Tests for list comparison methods were added

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
Closes: #137 
list.concat already returns list
> 137 concat is list

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> list.last-index-of implemented

- src/main/eo/org/eolang/collections/list.eo
> Optimized `list.reducedi` (#135)

- src/main/eo/org/eolang/collections/map.eo
- src/test/eo/org/eolang/collections/map-tests.eo
> map.contains-key implemented

- pom.xml
- src/main/eo/org/eolang/collections/list.eo
- src/main/eo/org/eolang/collections/map.eo
- src/main/eo/org/eolang/collections/multimap.eo
> #153 rename array to tuple

- src/main/eo/org/eolang/collections/list.eo
- src/test/eo/org/eolang/collections/list-tests.eo
> Add `list.withi`
